apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: spawner
build:
  local:
    push: false
  artifacts:
  - image: ghcr.io/drifting-in-space/spawner-controller
    context: crates
    docker:
      dockerfile: _containers/controller.Dockerfile
      cacheFrom:
      - ghcr.io/drifting-in-space/spawner-controller:latest
  - image: ghcr.io/drifting-in-space/spawner-api
    context: crates
    docker:
      dockerfile: _containers/api.Dockerfile
      cacheFrom:
      - ghcr.io/drifting-in-space/spawner-api:latest
  - image: ghcr.io/drifting-in-space/spawner-sweeper
    context: crates
    docker:
      dockerfile: _containers/sweeper.Dockerfile
      cacheFrom:
        - ghcr.io/drifting-in-space/spawner-sweeper:latest
  - image: ghcr.io/drifting-in-space/spawner-sidecar
    context: crates
    docker:
      dockerfile: _containers/sidecar.Dockerfile
      cacheFrom:
        - ghcr.io/drifting-in-space/spawner-sidecar:latest
deploy:
  kubeContext: minikube
  kustomize:
    paths:
    - cluster
