apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: spawner
build:
  local:
    push: false
  artifacts:
  - image: ghcr.io/drifting-in-space/spawner-controller
    context: crates
    custom:
      buildCommand: _containers/build.sh _containers/controller.Dockerfile
  - image: ghcr.io/drifting-in-space/spawner-api
    context: crates
    custom:
      buildCommand: _containers/build.sh _containers/api.Dockerfile
  - image: ghcr.io/drifting-in-space/spawner-sidecar
    context: crates
    custom:
      buildCommand: _containers/build.sh _containers/sidecar.Dockerfile
  - image: ghcr.io/drifting-in-space/spawner-sweeper
    context: crates
    custom:
      buildCommand: _containers/build.sh _containers/sweeper.Dockerfile
deploy:
  kubeContext: minikube
  kustomize:
    paths:
    - cluster
