apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: spawner
build:
  local:
    push: false
  artifacts:
  - image: ghcr.io/drifting-in-space/spawner-controller
    context: crates
    custom:
      buildCommand: _containers/build.sh _containers/controller.Dockerfile
      dependencies:
        paths:
          - "controller"
          - "resource"
        ignore:
          - "controller/target"
          - "resource/target"
  - image: ghcr.io/drifting-in-space/spawner-api
    context: crates
    custom:
      buildCommand: _containers/build.sh _containers/api.Dockerfile
      dependencies:
        paths:
          - "api"
          - "resource"
        ignore:
          - "api/target"
          - "resource/target"
  - image: ghcr.io/drifting-in-space/spawner-sidecar
    context: crates
    custom:
      buildCommand: _containers/build.sh _containers/sidecar.Dockerfile
      dependencies:
        paths:
          - "sidecar"
        ignore:
          - "sidecar/target"
  - image: ghcr.io/drifting-in-space/spawner-sweeper
    context: crates
    custom:
      buildCommand: _containers/build.sh _containers/sweeper.Dockerfile
      dependencies:
        paths:
          - "sweeper"
          - "resource"
        ignore:
          - "sweeper/target"
          - "resource/target"
deploy:
  kubeContext: minikube
  kustomize:
    paths:
    - cluster
