apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sweeper
  labels:
    app: sweeper
spec:
  selector:
    matchLabels:
      app: sweeper
  template:
    metadata:
      labels:
        app: sweeper
    spec:
      serviceAccountName: spawner
      containers:
      - name: spawner
        image: ghcr.io/drifting-in-space/spawner-sweeper:latest
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: RUST_LOG
            value: "debug,hyper=info,tower=info"
        args: [
          "--namespace", "spawner",
          "--node-name", "$(POD_NAME)"
        ]
