[package]
name = "spawner-sidecar"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
hyper = {version="0.14.16", features=["full"]}
tokio = { version = "1.15.0", features = ["full"] }
