resources:
- resources/spawner.yaml
- resources/nginx.yaml
- resources/sweeper.yaml
- resources/sessionlivedbackend.yaml
configMapGenerator:
- name: nginx-config
  files:
  - config/nginx/default.conf
  - config/nginx/index.html