---
apiVersion: spawner.dev/v1
kind: SessionLivedBackend
metadata:
  generateName: spawner-
  namespace: spawner
spec:
  template:
    containers:
      - env: []
        image: "ghcr.io/drifting-in-space/demo-image-drop-four:latest"
        name: application
  gracePeriodSeconds: 300

